name = "MMSBAnalyzerJulia"
uuid = "5d1bcbb7-52cb-4e3d-8bc3-1e39242e66d3"
version = "0.1.0"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
JSON = "1.3.0"
MacroTools = "0.5.16"
